all: main

main: main.c card.c cardAction.c change_cardinhand.c checkIfFollowingCard.c clear_screen.c could_play.c deck.c demo_input0.c demo_playcards.c end_the_round.c fprint_card.c fprint_deck.c gocontinue.c if_clear.c init_game.c isWin.c onecard.c
	gcc main.c card.c cardAction.c change_cardinhand.c checkIfFollowingCard.c clear_screen.c could_play.c deck.c demo_input0.c demo_playcards.c end_the_round.c fprint_card.c fprint_deck.c gocontinue.c if_clear.c init_game.c isWin.c onecard.c -o main -O2 -Werror -Wall -Wextra -Wconversion -Wvla -Wpedantic

clean:
	rm -f main